name: Update Landing Page
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  build-and-deploy:
    uses: curvenote/actions/.github/workflows/push.yml@v1
    with:
      landing-content: ncssm-mor
    secrets:
      CURVENOTE: ${{ secrets.CURVENOTE_TOKEN }}
